### ISSUE TITLE
There is no mention of "pasta" on the install page, only "slirp4netns"

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman.io#285]
https://podman.io/docs/installation

So it ends up missing, in the `info`

```
  pasta:
    executable: ""
    package: ""
    version: ""
```

But podman runs OK, with slirp4netns.

```
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_100:1.1.8-4_amd64
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
```

----

* https://github.com/containers/podman/issues/22015#issuecomment-1991964833

Apparently you need some special version of "pasta", but there are no feature or version checks for it
